### ISSUE TITLE
Statistical significance tests

### ISSUE THREAD

**Issue by lily706** [toonvds/CostSensitiveLearning#3]
Hi, 

Can you please share your code for the critical difference diagrams and the statistical tests you used? I'm still a beginner and not sure how to do that and didn't find some code online.

Thanks a million, it would help a lot!

**Comment by toonvds** [comment]
Hi! 

I used the "`compute_CD`" and `"graph_ranks"` functions from `Orange` for the critical difference diagrams, and the `"wilcoxon"` and `"friedmanchisquare"` functions from `scipy` for additional testing. 

I hope this helps!

**Comment by lily706** [comment]
Hi! It does, I'll try to implement it and see how it goes, thanks a lot! 
Can you please tell me where you used Wilcoxon exactly in your experiments?

**Comment by lily706** [comment]
Hi again,

I tried testing Orange but it looks like it's deprecated, the functions no longer exist in Orange3. Do you mind sharing the version you used?

Can you also tell me where you used Wilcoxon test? And which test did you use to determine the values in bold and italic in Table 9 of your paper?

Much appreciated!

**Comment by toonvds** [comment]
The Orange version was the following `Orange3==3.27.1`, see also the requirements file. 

The Wilcoxon test was used for the results in the tables for a pairwise comparison with the best result.

**Comment by lily706** [comment]
Thanks a lot!
